import type { ToolOption, ToolOptions } from '@/hooks/useToolState';

export const TAILWIND_OPTIONS: ToolOption[] = [
  { key: 'filter', label: 'Search', type: 'text', default: '', placeholder: 'Filter by class or CSS...' },
];

const MAP: ReadonlyArray<readonly [string, string]> = [
  ['flex', 'display: flex'],
  ['inline-flex', 'display: inline-flex'],
  ['block', 'display: block'],
  ['inline-block', 'display: inline-block'],
  ['inline', 'display: inline'],
  ['hidden', 'display: none'],
  ['grid', 'display: grid'],
  ['inline-grid', 'display: inline-grid'],
  ['table', 'display: table'],
  ['contents', 'display: contents'],
  ['flex-row', 'flex-direction: row'],
  ['flex-col', 'flex-direction: column'],
  ['flex-wrap', 'flex-wrap: wrap'],
  ['flex-1', 'flex: 1 1 0%'],
  ['items-center', 'align-items: center'],
  ['items-start', 'align-items: flex-start'],
  ['items-end', 'align-items: flex-end'],
  ['justify-center', 'justify-content: center'],
  ['justify-between', 'justify-content: space-between'],
  ['justify-around', 'justify-content: space-around'],
  ['gap-2', 'gap: 0.5rem'],
  ['gap-4', 'gap: 1rem'],
  ['p-2', 'padding: 0.5rem'],
  ['p-4', 'padding: 1rem'],
  ['px-4', 'padding-left: 1rem; padding-right: 1rem'],
  ['py-2', 'padding-top: 0.5rem; padding-bottom: 0.5rem'],
  ['m-2', 'margin: 0.5rem'],
  ['m-4', 'margin: 1rem'],
  ['mt-4', 'margin-top: 1rem'],
  ['mb-2', 'margin-bottom: 0.5rem'],
  ['mx-auto', 'margin-left: auto; margin-right: auto'],
  ['text-left', 'text-align: left'],
  ['text-center', 'text-align: center'],
  ['text-right', 'text-align: right'],
  ['text-xs', 'font-size: 0.75rem'],
  ['text-sm', 'font-size: 0.875rem'],
  ['text-base', 'font-size: 1rem'],
  ['text-lg', 'font-size: 1.125rem'],
  ['text-xl', 'font-size: 1.25rem'],
  ['font-normal', 'font-weight: 400'],
  ['font-medium', 'font-weight: 500'],
  ['font-semibold', 'font-weight: 600'],
  ['font-bold', 'font-weight: 700'],
  ['uppercase', 'text-transform: uppercase'],
  ['lowercase', 'text-transform: lowercase'],
  ['truncate', 'overflow: hidden; text-overflow: ellipsis; white-space: nowrap'],
  ['w-full', 'width: 100%'],
  ['w-screen', 'width: 100vw'],
  ['h-full', 'height: 100%'],
  ['h-screen', 'height: 100vh'],
  ['min-h-screen', 'min-height: 100vh'],
  ['max-w-full', 'max-width: 100%'],
  ['rounded', 'border-radius: 0.25rem'],
  ['rounded-lg', 'border-radius: 0.5rem'],
  ['rounded-full', 'border-radius: 9999px'],
  ['border', 'border-width: 1px'],
  ['border-2', 'border-width: 2px'],
  ['absolute', 'position: absolute'],
  ['relative', 'position: relative'],
  ['fixed', 'position: fixed'],
  ['sticky', 'position: sticky'],
  ['static', 'position: static'],
  ['opacity-0', 'opacity: 0'],
  ['opacity-50', 'opacity: 0.5'],
  ['opacity-100', 'opacity: 1'],
  ['z-0', 'z-index: 0'],
  ['z-10', 'z-index: 10'],
  ['z-50', 'z-index: 50'],
  ['overflow-hidden', 'overflow: hidden'],
  ['overflow-auto', 'overflow: auto'],
  ['cursor-pointer', 'cursor: pointer'],
  ['select-none', 'user-select: none'],
];

export function buildTailwind(options: ToolOptions): string {
  const q = String(options.filter ?? '').trim().toLowerCase();
  const list = q
    ? MAP.filter(([c, css]) => c.toLowerCase().includes(q) || css.toLowerCase().includes(q))
    : MAP;
  return list.length ? list.map(([c, css]) => `${c}  ->  ${css}`).join('\n') : 'No matches.';
}
