import type { ToolOption, ToolOptions } from '@/hooks/useToolState';

export const GITIGNORE_OPTIONS: ToolOption[] = [
  {
    key: 'template',
    label: 'Template',
    type: 'select',
    default: 'node',
    choices: [
      { value: 'node', label: 'Node' },
      { value: 'python', label: 'Python' },
      { value: 'java', label: 'Java' },
      { value: 'go', label: 'Go' },
      { value: 'rust', label: 'Rust' },
      { value: 'macos', label: 'macOS' },
    ],
  },
];

const TEMPLATES: Record<string, string> = {
  node: [
    '# Dependencies',
    'node_modules/',
    '',
    '# Build output',
    'dist/',
    'build/',
    '',
    '# Logs',
    'npm-debug.log*',
    'yarn-debug.log*',
    'yarn-error.log*',
    'pnpm-debug.log*',
    '',
    '# Environment',
    '.env',
    '.env.local',
    '.env.*.local',
    '',
    '# Misc',
    '.DS_Store',
    'coverage/',
    '.cache/',
  ].join('\n'),
  python: [
    '# Byte-compiled / optimized / DLL files',
    '__pycache__/',
    '*.py[cod]',
    '*.pyc',
    '',
    '# Distribution / packaging',
    'build/',
    'dist/',
    '*.egg-info/',
    '',
    '# Virtual environments',
    '.venv',
    'venv/',
    'env/',
    '',
    '# Environment',
    '.env',
    '',
    '# Testing / coverage',
    '.pytest_cache/',
    '.coverage',
    'htmlcov/',
  ].join('\n'),
  java: [
    '# Compiled class files',
    '*.class',
    '',
    '# Build directories',
    'target/',
    'build/',
    'out/',
    '',
    '# Package files',
    '*.jar',
    '*.war',
    '*.ear',
    '',
    '# Logs',
    '*.log',
    '',
    '# IDE',
    '.idea/',
    '*.iml',
  ].join('\n'),
  go: [
    '# Binaries',
    '/bin/',
    '*.exe',
    '*.dll',
    '*.so',
    '*.dylib',
    '',
    '# Test binary and coverage',
    '*.test',
    '*.out',
    'coverage.txt',
    '',
    '# Dependency directories',
    'vendor/',
    '',
    '# Go workspace file',
    'go.work',
  ].join('\n'),
  rust: [
    '# Build output',
    '/target',
    '',
    '# Backup files',
    '**/*.rs.bk',
    '',
    '# Remove Cargo.lock from gitignore if creating an executable, leave for libraries',
    '# Cargo.lock',
  ].join('\n'),
  macos: [
    '# General',
    '.DS_Store',
    '.AppleDouble',
    '.LSOverride',
    '',
    '# Thumbnails',
    '._*',
    '',
    '# Files that might appear in the root of a volume',
    '.DocumentRevisions-V100',
    '.fseventsd',
    '.Spotlight-V100',
    '.Trashes',
  ].join('\n'),
};

export function buildGitignore(options: ToolOptions): string {
  const template = String(options.template ?? 'node');
  return TEMPLATES[template] ?? TEMPLATES.node;
}
